all: part1 part2 part3 part4

part1:
	gcc -g part1.c -o part1.exe

part2:
	gcc -g part2.c -o part2.exe

part3:
	gcc -g part3.c -o part3.exe

part4:
	gcc -g part4.c -o part4.exe

clean:
	rm part1.exe part2.exe part3.exe part4.exe